package datagen

import (
	"encoding/base64"
	"encoding/hex"
	"strings"
	"testing"

	s3vectors "github.com/cloud-portable/s3vectors/packages/go"
)

// Independently computed check values shared by all four language ports.
const (
	block0 = "b8cc3d1fcf7818feab07f224263256110eeb3b576a94ef8e7e439b48fc77998b"
	block1 = "64a3a04c326aae7efd121f8468df1ac90ead2ece1e952353903cbcb6ae47618d"
)

func str(s string) *string { return &s }

var specs = map[string]s3vectors.DataSpec{
	"t40":   {Prng: &s3vectors.PrngData{Seed: "test", Size: 40}},
	"t32":   {Prng: &s3vectors.PrngData{Seed: "test", Size: 32}},
	"t10":   {Prng: &s3vectors.PrngData{Seed: "test", Size: 10}},
	"aaa":   {Pattern: &s3vectors.PatternData{Pattern: str("A"), Size: 5}},
	"abc":   {Pattern: &s3vectors.PatternData{Pattern: str("abc"), Size: 8}},
	"bin":   {Pattern: &s3vectors.PatternData{PatternBase64: str("3q2+7w=="), Size: 6}},
	"sl":    {Slice: &s3vectors.SliceData{Of: "t40", Offset: 30, Length: 6}},
	"chain": {Slice: &s3vectors.SliceData{Of: "sl", Offset: 0, Length: 1}},
	"over":  {Slice: &s3vectors.SliceData{Of: "t10", Offset: 8, Length: 8}},
	"check": {Pattern: &s3vectors.PatternData{Pattern: str("123456789"), Size: 9}},
}

func mustGenerate(t *testing.T, name string) []byte {
	t.Helper()
	b, err := Generate(specs, name)
	if err != nil {
		t.Fatalf("Generate(%s): %v", name, err)
	}
	return b
}

func mustDerived(t *testing.T, name, field string) string {
	t.Helper()
	s, err := Derived(specs, name, field)
	if err != nil {
		t.Fatalf("Derived(%s, %s): %v", name, field, err)
	}
	return s
}

func b64OfHex(t *testing.T, h string) string {
	t.Helper()
	raw, err := hex.DecodeString(h)
	if err != nil {
		t.Fatal(err)
	}
	return base64.StdEncoding.EncodeToString(raw)
}

func TestCheckValues(t *testing.T) {
	stream40 := block0 + block1[:16]
	cases := []struct{ name, wantHex string }{
		{"t32", block0},
		{"t40", stream40},
		{"t10", block0[:20]},
		{"bin", "deadbeefdead"},
		{"sl", stream40[60:72]},
	}
	for _, c := range cases {
		if got := hex.EncodeToString(mustGenerate(t, c.name)); got != c.wantHex {
			t.Errorf("%s = %s, want %s", c.name, got, c.wantHex)
		}
	}
	if got := string(mustGenerate(t, "aaa")); got != "AAAAA" {
		t.Errorf("aaa = %q", got)
	}
	if got := string(mustGenerate(t, "abc")); got != "abcabcab" {
		t.Errorf("abc = %q", got)
	}

	derivedCases := []struct{ name, field, want string }{
		{"aaa", "md5", "f6a6263167c92de8644ac998b3c4e4d1"},
		{"aaa", "etag", `"f6a6263167c92de8644ac998b3c4e4d1"`},
		{"aaa", "size", "5"},
		// CRC catalog check values over ASCII "123456789"
		{"check", "crc32B64", b64OfHex(t, "cbf43926")},
		{"check", "crc32cB64", b64OfHex(t, "e3069283")},
		{"check", "crc64nvmeB64", b64OfHex(t, "ae8b14860a799888")},
	}
	for _, c := range derivedCases {
		if got := mustDerived(t, c.name, c.field); got != c.want {
			t.Errorf("derived(%s, %s) = %s, want %s", c.name, c.field, got, c.want)
		}
	}
	for _, f := range DerivedFields {
		mustDerived(t, "sl", f)
	}
}

func TestErrorCases(t *testing.T) {
	cases := []struct {
		run  func() error
		want string
	}{
		{func() error { _, err := Generate(specs, "nope"); return err }, "unknown dataset"},
		{func() error { _, err := Derived(specs, "aaa", "sha512"); return err }, "unknown derived data field"},
		{func() error { _, err := Generate(specs, "chain"); return err }, "chained slices"},
		{func() error { _, err := Generate(specs, "over"); return err }, "exceeds"},
	}
	for _, c := range cases {
		err := c.run()
		if err == nil || !strings.Contains(err.Error(), c.want) {
			t.Errorf("want error containing %q, got %v", c.want, err)
		}
	}
}

func TestFullCorpusDatagen(t *testing.T) {
	// Every non-slice dataset up to generateCap must materialize (slice bounds
	// are corpus-linted). A dataset above the cap runs to gigabytes and no unit
	// test allocates that much; the corpus linter requires those to carry the
	// large tag, and the algorithms are size-independent and pinned by check
	// values above. Derived fields regenerate their dataset internally, so
	// exercise them only where the regenerated bytes are small.
	const generateCap = 1 << 26
	const derivedCap = 1 << 20
	all, err := s3vectors.All()
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range all {
		for i := range f.Vectors {
			v := &f.Vectors[i]
			if !v.IsAPI() || len(v.Data) == 0 {
				continue
			}
			for name, spec := range v.Data {
				var parentSize int64
				if spec.Slice != nil {
					parent := v.Data[spec.Slice.Of]
					if parent.Prng != nil {
						parentSize = parent.Prng.Size
					} else if parent.Pattern != nil {
						parentSize = parent.Pattern.Size
					}
				} else {
					if spec.Prng != nil {
						parentSize = spec.Prng.Size
					} else if spec.Pattern != nil {
						parentSize = spec.Pattern.Size
					}
					if parentSize <= generateCap {
						b, err := Generate(v.Data, name)
						if err != nil {
							t.Fatalf("%s/%s: %v", v.ID, name, err)
						}
						if int64(len(b)) != parentSize {
							t.Fatalf("%s/%s: size %d != %d", v.ID, name, len(b), parentSize)
						}
					}
				}
				if parentSize <= derivedCap {
					for _, field := range DerivedFields {
						if _, err := Derived(v.Data, name, field); err != nil {
							t.Fatalf("%s/%s.%s: %v", v.ID, name, field, err)
						}
					}
				}
			}
		}
	}
}
